
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincode-demo
  namespace: dummy-com
  labels: 
    chaincode: chaincode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      chaincode: chaincode-demo
  template:
    metadata:
      labels:
        chaincode: chaincode-demo
    spec:
      containers:
        - name: chaincode-demo
          image: tommystark/chaincode-as-external-service
          env:
            - name: CORE_CHAINCODE_ADDRESS
              value: 0.0.0.0:9999
            - name: CORE_CHAINCODE_ID
              value: chaincode-as-external-service:33b295bb4ac3f8dead7bddb9e86315aa7b3729b76d6d53f9379ddba6db900f7f
          ports:
            - containerPort: 9999
