---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-org1-dummy-com
  namespace: dummy-com
  labels: 
    component: "peer0.org1.dummy.com"
    type: peer
spec:
  replicas: 1
  serviceName: peer0-org1-dummy-com
  selector:
    matchLabels:
      component: "peer0.org1.dummy.com"
      type: peer
  template:
    metadata:
      labels:
        component: "peer0.org1.dummy.com"
        type: peer
    spec:
      volumes:
        - name: chaincode-buildpack
          persistentVolumeClaim:
            claimName: chaincode-buildpack
        - name: hlf-crypto-config
          persistentVolumeClaim:
            claimName: hlf-crypto-config
      containers:
        - name: couchdb-org1-dummy-com
          image: couchdb:3.2.2
          imagePullPolicy: IfNotPresent
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-org1-dummy-com
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-org1-dummy-com
                  key: password
          livenessProbe:
            httpGet:
              path: /
              port: 5984
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 5984
        - name: peer0-org1-dummy-com
          image: hyperledger/fabric-peer:2.4
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          env:
            - name: FABRIC_LOGGING_SPEC
              value: debug:cauthdsl,policies,msp,grpc,peer.gossip.mcs,gossip,leveldbhelper=info
            - name: CORE_PEER_ID
              value: peer0-org1-dummy-com
            - name: CORE_PEER_ADDRESS
              value: peer0-org1-dummy-com:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /var/hyperledger/peer/msp
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org1-dummy-com:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-org1-dummy-com:7051
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /var/hyperledger/peer/tls/ca.crt
            - name: CORE_PEER_TLS_CERT_FILE
              value: /var/hyperledger/peer/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /var/hyperledger/peer/tls/server.key
            - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
              value: peer0-org1-dummy-com
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: CouchDB
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: localhost:5984 # deployed in the same pod and using loopback to avoid performance issue
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchdb-org1-dummy-com
                  key: username
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-org1-dummy-com
                  key: password
          #
          # TODO: grpc probe ?
          # disabled as peer health check include docker
          #
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 9443
          #   initialDelaySeconds: 10
          #   failureThreshold: 3
          #   periodSeconds: 1
          #   timeoutSeconds: 1
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 9443
          volumeMounts:
            - name: chaincode-buildpack
              mountPath: /opt/buildpack/bin
              subPath: bin
            - name: chaincode-buildpack
              mountPath: /etc/hyperledger/fabric/core.yaml
              subPath: config/core.yaml
            - name: hlf-crypto-config
              mountPath: /var/hyperledger/peer/msp
              subPath: peerOrganizations/org1.dummy.com/peers/peer0.org1.dummy.com/msp
            - name: hlf-crypto-config
              mountPath: /var/hyperledger/peer/tls
              subPath: peerOrganizations/org1.dummy.com/peers/peer0.org1.dummy.com/tls
